---
title: "Quão grande é o meu [Deus]{.marked}"
format: 
  revealjs:
    theme: theme.scss
    width: 1600
    height: 900
    footer: "#JOVENSCAHo"
    fontsize: 100px
    transition: slide
    background-transition: fade
self-contained: true
---

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>

#

<center>
Com esplendor de um rei <br>
Em majestade e luz <br>
Faz a terra se alegrar <br>
Faz a terra se alegrar <br>
</center>

#

<center>
Ele é a própria luz <br>
E as trevas vão fugir <br>
Tremer com sua voz <br>
Tremer com sua voz <br>
</center>

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>

#

<center>
Por gerações ele é <br>
O tempo está em tuas mãos <br>
O começo e o fim, <br> o começo e o fim <br>
Três se formam em um <br>
Filho, Espírito e Pai <br>
Cordeiro e leão, cordeiro e leão <br>
</center>

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>

#

<center>
Sobre todo nome é o Seu <br>
Tu és digno do louvor <br>
Eu cantarei quão grande <br> é o meu [Deus]{.marked} <br>

É o meu [Deus]{.marked} <br>
</center>

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>

#

<center>
Quão grande é o meu [Deus]{.marked} <br>
Cantarei quão grande <br> é o meu [Deus]{.marked} <br>
E todos hão de ver <br>
Quão grande é o meu [Deus]{.marked} <br>
</center>