---
title: "Santo Espírito"
format: 
  revealjs:
    theme: theme.scss
    width: 1600
    height: 900
    footer: "#JOVENSCAHo"
    fontsize: 80px
    transition: slide
    background-transition: fade
self-contained: true
---

#

<center>
Nós pedimos Tua presença entre nós <br>
Santo Espírito de luz <br>
Vem, restaura em nós o Teu fogo abrasador <br>
Nos trazendo até Jesus <br>
</center>

#

<center>
Santo Espírito <br>
Enche este lugar! <br>
Enche este lugar <br>
Vive em nós! <br>
</center>

#

<center>
Santo Espírito <br>
Enche este lugar! <br>
Enche este lugar <br>
Vive em nós! <br>
</center>

#

<center>
Nós pedimos Tua presença entre nós <br>
Santo Espírito de luz <br>
Vem, restaura em nós o Teu fogo abrasador <br>
Nos trazendo até Jesus <br>
</center>

#

<center>
Santo Espírito <br>
Enche este lugar! <br>
Enche este lugar <br>
Vive em nós! <br>
</center>

#

<center>
Santo Espírito <br>
Enche este lugar! <br>
Enche este lugar <br>
Vive em nós! <br>
</center>

#

<center>
Venha a nós o Teu reino <br>
Seja feito o Teu querer <br>
Tua unção, Tua bênção <br>
Nós queremos receber <br>
</center>

#

<center>
Venha a nós o Teu reino <br>
Seja feito o Teu querer <br>
Tua unção, Tua bênção <br>
Nós queremos receber <br>
</center>

#

<center>
Venha a nós o Teu reino <br>
Seja feito o Teu querer <br>
Tua unção, Tua bênção <br>
Nós queremos receber <br>
</center>

#

<center>
Venha a nós o Teu reino <br>
Seja feito o Teu querer <br>
Tua unção, Tua bênção <br>
Nós queremos receber <br>
</center>

#

<center>
Santo Espírito <br>
Enche este lugar! <br>
Enche este lugar <br>
Vive em nós! <br>
</center>

#

<center>
Santo Espírito <br>
Enche este lugar! <br>
Enche este lugar
Vive em nós!
</center>

#

<center>
Enche este lugar!
Enche este lugar!
Enche este lugar
Vive em nós!
</center>
